cpsrapp/urls.py
from ast import Store
from email.mime import image
from venv import create
from django.contrib import admin
from django.urls import path, include
from cpsr.views import home, create, store, painel, mlogin, dashboard, mlogout, alterar_senha


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('create/', create),
    path('store/', store),
    path('painel/', painel),
    path('mlogin/', mlogin),
    path('dashboard/', dashboard),
    path('mlogout/', mlogout),
    path('alterar_senha/', alterar_senha, name='alterar_senha'),
    path('morador/', include('morador.urls')), 

 
 
    
]

morador/urls.py
from django.urls import path
from morador import views

app_name = 'morador'

urlpatterns = [
    path('', views.MoradorList.as_view(), name='list'),
    path('create/', views.MoradorCreate.as_view(), name='create'),
    path('update/<int:pk>/', views.MoradorUpdate.as_view(), name='update'),
    path('detail/<int:pk>/', views.MoradorDetail.as_view(), name='detail'),
    path('delete/<int:pk>/', views.MoradorDelete.as_view(), name='delete'),
]

morador/models.py
from django.db import models


sexo_psr = {
    ('F', 'FEMININO' ),
    ('M', 'MASCULINO')

}
tempoManau = {
    ('-1', 'Menos de 1 ano'),
    ('1a5', 'Entre 1 a 5 anos'),
    ('6a10', 'Entre 6 a 10 anos'),
    ('11a15', 'Entre 11 a 15 anos'),
    ('16+', 'Mais de 16 anos')
}

cor = {
    ('Branca', 'Branca'),
    ('Negra', 'Negro/Preta'),
    ('Parda', 'Parda'),
    ('Amarelo', 'Amarela'),
    ('indigena', 'Indigena')
}
class Morador(models.Model):

    ruaAbordagem = models.CharField(max_length=50, null=True, verbose_name='Rua Abordagem')
    bairroAbordagem = models.CharField(max_length=50, null=True, verbose_name='Bairro Abordagem')
    nome = models.CharField(max_length=50, null=True, verbose_name='Nome')
    apelido = models.CharField(max_length=30, null=True, verbose_name='Apelido')
    nomeMAe = models.CharField(max_length=50, null=True, verbose_name='Nome da Mãe')
    nomePai = models.CharField(max_length=50, null=True, verbose_name='Nome do Pai')
    idade = models.IntegerField(blank=True, null=True, verbose_name='Idade')
    sexo = models.CharField(max_length=10, choices=sexo_psr, null=True)
    cor = models.CharField(max_length=10, choices=cor, null=True)
    naturalidade = models.CharField(max_length=25, null=True, verbose_name='Naturalidade')
    tempoManaus = models.CharField(max_length=20, choices=tempoManau, null=True, verbose_name='Tempo em Manaus')
    rg = models.CharField(max_length=30, null=True, verbose_name='RG')
    cpf = models.CharField(max_length=11, null=True, verbose_name='CPF')
    cartaoSus = models.CharField(max_length=30, null=True, verbose_name='Cartão SUS')
    cadUnico = models.CharField(max_length=30, null=True, verbose_name='Cad. Único')
    last_update = models.DateTimeField(auto_now_add=False, auto_now=True, null=True, verbose_name='Última alteração')
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False, null=True, verbose_name='Data de Cadastro')


    def _str_(self):
        return self.nome

morador/forms.py
from django import forms

class MoradorForm(forms.ModelForms):
    class Meta:
        model = Morador
        fields = '__all__'

cpsr/views.py
from dataclasses import dataclass
import email
from email import message
from multiprocessing import context
from unicodedata import name
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm



# Create your views here.
def home(request):
    return render(request, 'home.html')

##Formumlário de usuários para cadastro.
def create(request):
    return render(request, 'create.html')

##inserindo dados de usuários no bd
def store(request):
    data = {}
    if(request.POST['password'] != request.POST['password-conf']):
        data['msg'] = 'As senhas não conferem!'
        data['class'] = 'alert-danger'
    else:
        user = User.objects.create_user(request.POST['name'], request.POST['email'], request.POST['password'])
        user.first_name = request.POST['name']
        user.save()
        data['msg'] = 'Usuário cadastrado com Sucesso'
        data['class'] = 'alert-sucess'    
    return render(request, 'create.html', data)

    ##Painel do Login.
def painel(request):
    return render(request, 'painel.html')

     ##Processamento de Login.
def mlogin(request):
    data = {}
    user = authenticate(username=request.POST['user'], password=request.POST['password'])
    if user is not None:
        login(request, user)
        return redirect('/dashboard/')
    else:
        data['msg'] = 'Usuário ou senha inválidos!'
        data['class'] = 'alert-danger'  
        return render(request, 'painel.html', data)

   ##Dashboard inicial da pagina test.
def dashboard(request):
    return render(request, 'dashboard/home.html')        


  ##logout do usuário no sistema. Ò_Ó'
def mlogout(request):
    logout(request)
    return redirect('/painel/')   


  ##Trocando a senha. Amém 3x 
  ##quebrado. funcional mas sem exibição da html
  ##finalizado
def alterar_senha(request):
    data = {}
    if request.method == "POST":
        form_senha = PasswordChangeForm(request.user, request.POST)
        if form_senha.is_valid():
            user = form_senha.save()
            update_session_auth_hash(request, user)
            data['msg'] = 'Senha alterada com Sucesso'
            data['class'] = 'alert-sucess' 
            return render(request, 'painel.html', data)
    else:
        form_senha = PasswordChangeForm(request.user)
    return render(request, 'alterar_senha.html', {'form_senha': form_senha})


   

morador/views.py
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.shortcuts import render
from morador.models import Morador
from django.urls import reverse_lazy

class MoradorList(ListView):
    model = Morador
    queryset = Morador.objects.all()

class MoradorCreate(CreateView):
    model = Morador
    fields = '__all__'
    success_url = reverse_lazy('morador:list')

class MoradorUpdate(UpdateView):
    model = Morador
    fields = '__all__'
    success_url = reverse_lazy('morador:list')

class MoradorDetail(DetailView):
    queryset = Morador.objects.all()

class MoradorDelete(DeleteView):
    queryset = Morador.objects.all()
    success_url = reverse_lazy('morador:list')

cpsr/templates/alterar_senha.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Alterar senha</title>
</head>

<body>
    <div class="login-box">
        
        <form method="post">
            <div class="col-7 col-sm-5 col-lg-3 col-xl-3 mx-auto m-auto login">
                <div class="login-box text-center">
                    <img src="{% static '/img/alterar_senha.jpg' %}" class="img-fluid" alt="" />
            {% csrf_token %}
            <div class="form-group  ">
                {{form_senha.old_password.errors}}
                <div class="span3">Senha antiga:<br>  {{form_senha.old_password}}</div>
            </div>

            <div class="form-group mt-4">
                {{form_senha.new_password1.errors}}
                <div class="span3">Nova senha:<br> {{form_senha.new_password1}}</div>
            </div>

            <div class="form-group mt-4">
                {{form_senha.new_password2.errors}}
                <div class="span3">Confirmação de senha:<br> {{form_senha.new_password2}}</div>
            </div>
<br>
            <div class="form-group text-center">
                <input type="submit" value="Alterar" class="btn btn-primary">
            </div>
            </div>
        </div>
        </form>
    </div>
    {% endblock %}

cpsr/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>CPSR - Cadastro de Pessoas em Situação de Rua</title>
  <link rel="icon" type="image/png" href="{% static '/img/favicon.ico' %}"/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous" />
  <link href="{% static '/css/base.css' %}" rel="stylesheet" />
  <nav class="navbar navbar-expand-lg navbar-light navbar-cpsr">
    <a class="navbar-brand" href="/">
      <img src="{% static '/img/logo-cpsr-retangulo.png' %}" width="100" height="50" class="d-inline-block align-center"
        alt="" />
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="/dashboard/">&nbsp;Página Inicial</a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="/">&nbsp;Página Inicial</a>
        </li>
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Cadastro
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/morador/create">Novo Cadastro</a>
            <a class="dropdown-item" href="/morador/">Visualizar Cadastros</a>
            <a class="dropdown-item" href="#">Importar Cadastro</a>
            <a class="dropdown-item" href="#">Relatórios</a>
          </div>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Configurações
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Perfil</a>
            <a class="dropdown-item" href="/alterar_senha/">Alterar Senha</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/mlogout/">Sair</a>
          </div>
      </li>
        <li class="nav-item pull-right">
          <a class="nav-item nav-link">&nbsp;Bem vindo(a), {{user.get_username}}</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/painel/">&nbsp;Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/create/">&nbsp;Cadastrar Usuário</a>
        </li>
      </ul>
      {% endif %}
    </div>
    </div>
  </nav>
</head>

<body>
  {% block content %} {% endblock %}


</body>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/javascript.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <footer>
    &nbsp;
    <div style="display: grid; grid-template-columns: 1fr 1fr ; background-color: #112030; color: white;">
    <div>&nbsp;
      <h3>&nbsp;&nbsp;&nbsp;Mapa do Site</h3>
      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Página inicial</p>
      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sobre</p>
      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cadastro</p>
      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Login</p>
    </div>
    <div>&nbsp;
      <h3>&nbsp;&nbsp;&nbsp;Contato</h3>
      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Telefone: (92) 9000-000</p>
      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Endereço: Rua 1, Bairro 0</p>
    </div>
  </div>
  <span class="d-flex justify-content-center" style="background-color: #112030; color: white;">
  <p>Todos os direitos reservados 2022</p>
  </span>
  </footer>
</html>

cpsr/templates/changepassword.html
{% extends 'base.html' %}

{% block content %}
   <form name="formPassword" id="formPassword" method="post" action="/password/">
        <div class="col-6 mt-4 m-auto">
            {% if msg %}
                <div class="alert {{class}}">
                    {{msg}}
                </div>
            {% endif %}
            
            {% csrf_token %}         
            <input class="form-control mt-4" type="password" name="changePassword" id="changePassword" placeholder="Nova Senha"><br>       
            <input class="btn btn-dark mt-4" type="submit" value="Alterar">        
            
        </div>
   </form>
{% endblock %}

cpsr/templates/create.html
{% extends 'base.html' %} 
{% block content %} 
{% load static %}
   <form name="form-users" id="formUsers" method="post" action="/store/">
        <div class="col-8 col-sm-6 col-lg-3 col-xl-3 mx-auto m-auto login">
            {% if msg %}
                <div class="alert {{class}}">
                    {{msg}}
                </div>
            {% endif %}
            
            {% csrf_token %}
            <div class="login-box text-center">
            <img src="{% static '/img/cadastro-usuario.jpg' %}" class="img-fluid" alt="" />
            <input class="form-control mt-4" type="text" name="name" id="name" placeholder="Nome">        
            <input class="form-control mt-4" type="text" name="user" id="name" placeholder="Nome do Usuário">        
            <input class="form-control mt-4" type="password" name="password" id="password" placeholder="Senha">        
            <input class="form-control mt-4" type="password" name="password-conf" id="password" placeholder="Repita a Senha">        
            <input class="form-control mt-4" type="email" name="email" id="email" placeholder="Email">        
            <input class="btn btn-primary mt-4" type="submit" value="Cadastrar">        
        </div>
        </div>
   </form>
{% endblock %}

cpsr/templates/dashboard/cpassword.html
{% extends 'base.html' %}

{% block content %}
   <div class="container">
    <h1>Alterar senha do usuário</h1>
    <form method="POST">
        {% csrf_token %}
        <p><label for="id_old_password">Antiga senha</label> <input type="password" name="old_password" autofocus required id="id_old_password"></p>
        <p><label for="id_old_password">Nova senha</label> <input type="password" name="new_password1" required id="id_new_password1"> <span class="helptext"><ul><li>Sua senha não pode ser uma senha comum!</li></ul></span></p>
        <p><label for="id_old_password">Confirmar nova senha</label> <input type="password" name="new_password2" autofocus required id="id_new_password2"></p>
            <button type="submit">Alterar Senha</button>
    </form>
   </div>
{% endblock %}

cpsr/templates/dashboard/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if request.user.is_authenticated %}
    <div class="titulo">
        <h3>Cadastro de Pessoas em Situação de Rua - CPSR</h3>
      </div>
      <div class="container d-flex justify-content-center box-home">
        <div style="width: 30%">
            <img
          src="{% static '/img/cadastro.jpg' %}"
          class="img-fluid"
          alt=""
        />
        <a href="/morador/create/" style="text-decoration: none;">
          <h3>
            Cadastro de Pessoas
          </h3>
        </a>
    </div>
    <div style="width: 30%;">
        <img
          src="{% static '/img/relatorios.jpg' %}"
          class="img-fluid"
          alt=""
        />
        <a href="/morador/" style="text-decoration: none;">
          <h3>
            Relatórios
          </h3>
        </a>
    </div>
</div>

    {% else %}
    Acesso Negado! Realize o login para continuar.
    {% endif %}

    
{% endblock %}

cpsr/templates/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" style="height: 100%">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static '/img/slide1.png' %}" alt="">
      </div>
    </div>
  </div>
</div>
<div class="titulo container-home home-box" style="display: flex;" >
  <div>
    <a>
      <img src="{% static '/img/home-imagem.png' %}" class="img-fluid" style="width: 30rem" alt="" />
    </a>
  </div>
  <div style="width: 60%;">
    <h1>Sobre</h1>
    <p>Proporcionar a saída de pessoas da situação de rua tornou-se
      um dos maiores desafios que as grandes cidades de todo o mundo
      vêm enfrentando atualmente. No Brasil, a inclusão social do segmento em situação de rua tem sido prioridade e vem
      demandando esforços por parte de todas as esferas de governo. </p>
    <h1>Quem é a população
      em situação de rua?</h1>
    <p>A população em situação de rua é resultado do contexto de desigualdades sociais que caracterizam um sistema de
      violação de direitos. É um
      grupo populacional heterogêneo, composto por pessoas com diferentes
      realidades, mas que têm em comum a condição de pobreza absoluta, vínculos interrompidos ou fragilizados e
      inexistência de moradia convencional regular, sendo compelidas a utilizarem a rua como espaço de moradia e
      sustento, por contingência temporária ou de forma permanente.</p>
  </div>
  
</div>
<div class="container-home titulo2">
  <div style="padding: 3rem">
    <a>
      <img src="{% static '/img/polls.jpg' %}" class="img-fluid" style="width: 25rem" alt="" />
    </a>
  </div>
  <div class="home-box">
    <h3>Não possui Cadastro?</h3>
    <a class="btn btn btn-outline-primary" href="/create/">Cadastre-se Aqui</a><br /><br />
    <h3>Já possui?</h3>
    <a class="btn btn btn-outline-primary" href="/painel/">Faça o Login</a><br /><br />
  </div>
</div>

{% endblock %}

cpsr/templates/index.html
{% extends 'base.html' %}

{% block content %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>
    <h1>Área do Usuário</h1>

</body>

{% endblock %}

cpsr/templates/morador/morador_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% if request.user.is_authenticated %}


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Excluir Cadastro</title>
</head>

<body>
    <h1>Tem certeza que deseja excluir o cadastro do morador '{{ object.nome }}'?:</h1>
    <form action="." method="post">
        {% csrf_token %}
        <input class="btn btn-primary" type="submit" value="Sim, tenho certeza">
        <input class="btn btn-primary" type="reset" value="Cancelar" onclick="location.href = '{% url 'morador:list' %}'">
    </form>
</body>

{% else %}
Acesso Negado! Realize o login para continuar.

{% endif %}
{% endblock %}

cpsr/templates/morador/morador_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% if request.user.is_authenticated %}


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <center>
    <h1>{{ object.nome }}</h1>
    </center>
</head>

<body>
    <center>
        <b>Local da Abordagem</b>
        <br />
        Rua: {{ object.ruaAbordagem }}
        <br />
        Bairro: {{ object.bairroAbordagem }}
        <br />
        <b>Dados Pessoais</b>
        <br />
        Nome: {{ object.nome }}
        <br />
        Apelido: {{ object.apelido }}
        <br />
        Idade: {{ object.idade }}
        <br />
        Sexo: {{ object.sexo }}
        <br />
        Cor: {{ object.cor }}
        <br />    
        Naturalidade: {{ object.naturalidade }}
        <br />
        Nome da Mãe: {{ object.nomeMAe }}
        <br />
        Nome do Pai: {{ object.nomePai }}
        <br />
        <b>Documentos</b>
        <br />
        RG: {{ object.rg }}
        <br />
        CPF: {{ object.cpf }}
        <br />
        Cartão SUS: {{ object.cartaoSus }}
        <br />
        Cad Único: {{ object.cadUnico }}
        <br />
        Tempo em Manaus: {{ object.tempoManaus}}
        <br />
        <b>Informações Adicionais</b>
        <br />
        Última alteração: {{ object.last_update }}
        <br />
        Data de Cadastro: {{ object.timestamp }}
        <br />
    </center>

</body>


{% else %}
Acesso Negado! Realize o login para continuar.

{% endif %}

{% endblock %}

cpsr/templates/morador/morador_form.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% if request.user.is_authenticated %}


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastrar Morador</title>
</head>

<body>
    <center>
    <h1>Cadastro de Pessoas em Situação de Rua</h1>
    </center>
    <form method="post" action=".">
        <div class="col-8 col-sm-6 col-lg-3 col-xl-3 mx-auto m-auto login">
            {% csrf_token %}
            <div class="login-box text-center">
                {{ form.as_p }}

                <input class="btn btn-primary" type="submit" value="Salvar">
                <input class="btn btn-primary" type="reset" value="Cancelar" onclick="location.href = '{% url 'morador:list' %}'">
            </div>
        </div>
    </form>

</body>

{% else %}
Acesso Negado! Realize o login para continuar.

{% endif %}
{% endblock %}

cpsr/templates/morador/morador_list.html
{% extends 'base.html' %} 
{% block content %} 
{% load static %}
{% if request.user.is_authenticated %}


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h1>Cadastros de Pessoas em Situação de Rua</h1>
<input class="btn btn-primary" type="submit" onclick="location.href = '{% url 'morador:create' %}'" value="Criar novo Cadastro">
<div class="col-13 col-sm-11 col-lg-8 col-xl-8">
    <br>
<table class="table">
    <tr>
        <th>Nome</th>     
        <th>Idade</th>
        <th>Bairro</th>
        <th>Data de Cadastro</th>
        <th>Data de Atualização</th>
        <th>Ação</th>
    </tr>
    <tr>
    {% for morador in object_list %}
    <td>{{ morador.nome }}</td>
    <td>{{ morador.idade }}</td>
    <td>{{ morador.bairroAbordagem }}</td>
    <td>{{ morador.timestamp }}</td>
    <td>{{ morador.last_update }}</td>
    <td><a class="btn btn-primary" href="{% url 'morador:update' pk=morador.id %}">Editar</a>
        <a class="btn btn-primary" href="{% url 'morador:detail' pk=morador.id %}">Visualizar</a> 
        <a class="btn btn-danger" href="{% url 'morador:delete' pk=morador.id %}">Excluir</a>
    </td>
    </tr>
    {% endfor %}
</table>
    
</div>
    
</body>


{% else %}
Acesso Negado! Realize o login para continuar.

{% endif %}

{% endblock %}

cpsr/templates/painel.html
{% extends 'base.html' %} 
{% block content %} 
{% load static %}
<div class="align-items-center">
   <form name="formPainel" id="formPainel" method="post" action="/mlogin/">
        <div class="col-8 col-sm-6 col-lg-3 col-xl-3 mx-auto m-auto login">
            {% if msg %}
                <div class="alert {{class}}">
                    {{msg}}
                </div>
            {% endif %}
            
            {% csrf_token %}  
            <div class="login-box text-center">
            <img src="{% static '/img/login.jpg' %}" class="img-fluid" alt="" />
            <input class="form-control mt-4" type="text" name="user" id="name" placeholder="Nome do Usuário">        
            <input class="form-control mt-4" type="password" name="password" id="password" placeholder="Senha">   
            <input class="btn btn-dark mt-4 " type="submit" value="Entrar">
            <div style="display: flex text-center">
            <a class="btn btn-light" href="/create/">Primeiro acesso</a>&nbsp;
            </div>
            </div>     
            
        </div>
   </form>
</div>
{% endblock %}